### ISSUE TITLE
Doesn't compile on Axum 0.6.0-rc2

### ISSUE THREAD

**Issue by bigknife** [Owez/axum-auth#7]
error: 

the trait `Handler<_, _, _>` is not implemented for `fn(Extension<NotifyApplication>, HeaderMap, AuthBasic, axum::Json<Notification>) -> impl Future<Output = impl IntoResponse> {push}`

**Comment by Owez** [comment]
Thanks for making the issue, I'll handle this in the next few days and publish as `0.4.0`. I'll be hitting this error soon when I upgrade my projects.

**Comment by Congyuwang** [comment]
#9

**Comment by Owez** [comment]
Fixed via #9, thanks to @Congyuwang for the PR
