### ISSUE TITLE
ability to adjust rejection

### ISSUE THREAD

**Issue by Zerowalker** [Owez/axum-auth#8]
Currently it just fails with a `Bad Request`.

It would be useful if one could change it to set the header `WWW-Authorization`  with `Basic` and status `UNAUTHORIZED` to trigger the client to specify the missing `Authorization` header.

**Comment by Owez** [comment]
This will probably be implemented as something like `AuthBearerCustom` and `AuthBasicCustom` so you can change a few options but still have a nice default option without needing to pass something like a `Config::default`

**Comment by Owez** [comment]
Completed in #10 via 1d8ec195485f108c6ef3648a4ccee0d3e2b7f524
